apiVersion: v1
kind: Service
metadata:
  name: factura
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: factura
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factura
spec:
  selector:
    matchLabels:
      app: factura
  replicas: 1
  template:
    metadata:
      labels:
        app: factura
    spec:
      containers:
      - name: factura
        image: salomedev/factura:115
        ports:
        - containerPort: 80
        env:
        - name: INVOICE_SERVICE_ENDPOINT
          value: "http://173.212.252.61:4001"
