apiVersion: apps/v1
kind: Deployment
metadata:
  name: factura-deployment
spec:
  selector:
    matchLabels:
      app: factura-app
  replicas: 1
  template:
    metadata:
      labels:
        app: factura-app
    spec:
      containers:
      - name: factura
        image: salomedev/factura:115
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: factura-app
  name: factura-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: factura-app

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: facturasvc-ingress
spec:
  rules:
  - host: factura.daphneprojects.online
    http:
      paths:
      - backend:
          serviceName: factura-svc
          servicePort: 80
