apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoicesvc-deployment
spec:
  selector:
    matchLabels:
      app: invoicesvc-app
  replicas: 1
  template:
    metadata:
      labels:
        app: invoicesvc-app
    spec:
      containers:
      - name: invoicesvc
        image: salomedev/invoice-service:63
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: invoicesvc-app
  name: invoicesvc-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: invoicesvc-app

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: managerize-ingress
spec:
  rules:
  - host: invoiceservice.daphneprojects.online
    http:
      paths:
      - backend:
          serviceName: invoicesvc-svc
          servicePort: 80
