apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoicesvc-deployment
spec:
  selector:
    matchLabels:
      app: invoicesvc-app
  replicas: 1
  template:
    metadata:
      labels:
        app: invoicesvc-app
    spec:
      containers:
      - name: invoicesvc
        image: salomedev/invoice-service:63
        ports:
        - containerPort: 80
        env:
          - name: MANAGERIZE_INVOICE_SERVICE_DB
            value: "localhost"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: invoicesvc-app
  name: invoicesvc-svc
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: invoicesvc-app

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: managerize-ingress
spec:
  tls:
  - hosts:
    - daphneprojects.online
    - invoiceservice.daphneprojects.online
    - factura.daphneprojects.online
    secretName: managerize-crt
  rules:
  - host: invoiceservice.daphneprojects.online
    http:
      paths:
        backend:
          serviceName: invoicesvc-svc
          servicePort: 80
  - host: factura.daphneprojects.online
    http:
      paths:
        backend:
          serviceName: factura-svc
          servicePort: 80
