version: '3'
services: 
  wegister-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: wegister-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your(!)Strongpassword
    ports:
      - "1433:1433"

  wegister:
    image: salomedev/wegister:1
    container_name: wegister
    ports:
      - "57304:80"
    environment: 
      WEGISTERDB_CONNECTIONSTRING: 'Server=wegister-db;Initial Catalog=InvoiceServiceDb;User ID=sa;Password=Your(!)Strongpassword'