version: "3"
services:

  wegister:
    image: salomedev/wegister:1
    container_name: wegister
    ports:
      - "57304:80"
    environment: 
      WEGISTERDB_CONNECTIONSTRING: 'Server=173.212.252.62;Initial Catalog=WegisterDb;User ID=sa;Password=Managerize94!'