version: '3'
services: 
  invoiceservice-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: managerize-invoice-service-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your(!)Strongpassword
    ports:
      - "1433:1433"

  invoiceservice:
    image: salomedev/invoice-service:56
    container_name: managerize-invoiceservice
    ports:
      - "57304:80"
    environment: 
      MANAGERIZE_INVOICE_SERVICE_DB: 'Server=invoiceservice-db;Initial Catalog=InvoiceServiceDb;User ID=sa;Password=Your(!)Strongpassword'

  factura:
    container_name: managerize-factura
    build: . 
    ports:
      - "80:80"
    environment:
      INVOICE_SERVICE_ENDPOINT: 'invoice-service'